name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy
  - scipy
  - ipython
  - matplotlib
  - pandas
  - lxml
  - uncertainties
